### PR TITLE
Merge Charter into TDWG Repo

### PR DESCRIPTION
**Pull request by godfoder**
Making a pull request, my suggestion is to hold of on merging this until we're happy with the charter and the executive approves it.

### CODE REVIEW

**Comment by godfoder** [comment]
@stanblum Stan, can you merge this?

**Review by stanblum — APPROVED** [review]
This looks great.  Let's get this out to the rest of the IG and TG members for comment.

**Comment by stanblum** [comment]
All other members of the NCD Interest Group please comment.  Please open new issues for new suggested modifications.

**Comment by connierinaldo** [comment]
I agree this looks good.  I am not sure if it needs to be said explicitly but other objects that can be described in NCD include book or reprint collections.  Archives are cited (and somewhere we have a spreadsheet crosswalk to the Encoded Archival Description format).  Published materials are cited but I think this is too vague.  I could be splitting hairs but wanted to record my thoughts.

**Pull request merged**
